### ISSUE TITLE
DeepImageSearch: TensorFlow Issue

### ISSUE THREAD

**Issue by AtalKhandelwal** [TechyNilesh/DeepImageSearch#12]
Hi,
 When I tried to run the deep image search on my AWS EC2 ubuntu instance I'm getting the error 

 Allocation of 9437184 exceeds 10% of free system memory. Killed

Please let me know how should I handle this or what I'm missing

**Comment by qaixerabbas** [comment]
Maybe you are using an EC2 instance which has low memory. The TensorFlow package is a compute intensive one comparatively. I am not sure but increasing memory of EC2 may help.

**Comment by TechyNilesh** [comment]
> Hi, When I tried to run the deep image search on my AWS EC2 ubuntu instance I'm getting the error
> 
> Allocation of 9437184 exceeds 10% of free system memory. Killed
> 
> Please let me know how should I handle this or what I'm missing

The error message you are receiving indicates that your EC2 instance has run out of memory while running the deep image search, and the operating system has killed the process to prevent further memory consumption.

To resolve this issue, you can try the following steps:

Increase the memory limit for your EC2 instance: If your instance has a smaller amount of memory, you can try increasing its memory limit. You can do this by stopping the instance, selecting it, choosing "Actions" > "Instance Settings" > "Change Instance Type," and selecting a type with more memory.

Use a different instance type: If optimizing the code doesn't work, you can try using a different instance type with more memory. For example, you can use an instance type with higher memory or a GPU-enabled instance, which can significantly improve the performance of deep learning models.

I hope these steps will help you resolve the issue.
