### ISSUE TITLE
Index Error

### ISSUE THREAD

**Issue by matilda95** [TechyNilesh/DeepImageSearch#15]
Hi. thanks for this great work.
I'm getting this error and I can not manage to solve it. would you help? **line 266**

```
    264             axes.append(fig.add_subplot(grid_size, grid_size, a + 1))
    265             plt.axis('off')
--> 266             img = Image.open(img_list[a])
    267             img_resized = ImageOps.fit(img, (224, 224), Image.LANCZOS)
    268             plt.imshow(img_resized)

IndexError: list index out of range
```

**Comment by TechyNilesh** [comment]
I have updated the entire library. You can find the complete changelog here: https://github.com/TechyNilesh/DeepImageSearch/releases/tag/v_25. Bugs have been removed and additional features have been added.

**Comment by matilda95** [comment]
Thanks man. But unfortunately the error is still there. now in line **244.**

`
    242             axes.append(fig.add_subplot(grid_size, grid_size, a + 1))
    243             plt.axis('off')
--> 244             img = Image.open(img_list[a])
    245             img_resized = ImageOps.fit(img, (224, 224), Image.LANCZOS)
    246             plt.imshow(img_resized)

IndexError: list index out of range`


Maybe I'm doing something wrong?

**Comment by TechyNilesh** [comment]
Can ou show me your full code
*Thanks & Regards*
Nilesh Verma
Data Scientist and AI Researcher
*Amlgo Labs, India*
