### ISSUE TITLE
'image_features_vectors.ann' file don't get saved

### ISSUE THREAD

**Issue by ahmed0x77** [TechyNilesh/DeepImageSearch#16]
Whenever I try to index too many images like 80000, DeepImageSearch doesn't save  image_features_vectors.ann file 
and what's weird about it is that when I try to index like 2000 images it index fine and it save both .ann and .pkl files
also, I don't get any errors after the index 

here it what I get after the index :

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 86481/86481 [6:26:07<00:00,  3.73it/s]
Image Meta Information Saved: [meta-data-files/image_data_features.pkl]
9324it [01:28, 113.22it/s]
PS D:\3D>

**Comment by TechyNilesh** [comment]
I have updated the entire library. You can find the complete changelog here: https://github.com/TechyNilesh/DeepImageSearch/releases/tag/v_25.
Bugs have been removed and additional features have been added.
