### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by Zedomancer** [TechyNilesh/DeepImageSearch#17]
Whenever I try to import the initial command I get the following:
ImportError: cannot import name 'Load_Data' from 'DeepImageSearch'

Thank you for your work, I hope you can help.

**Comment by TechyNilesh** [comment]
I have updated the entire library. You can find the complete changelog here: https://github.com/TechyNilesh/DeepImageSearch/releases/tag/v_25.
Bugs have been removed and additional features have been added.
