### ISSUE TITLE
TypeError: show() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by mikedorin** [TechyNilesh/DeepImageSearch#6]
Classification.py:

from DeepImageSearch import Index, LoadData, SearchImage

folders = []
folders.append("monos_segmented")
image_list = LoadData().from_folder(folders)

print (image_list)

Index(image_list).Start()

SearchImage().get_similar_images(image_path=image_list[0],number_of_images=5)

SearchImage().plot_similar_images(image_path = image_list[0])

Running...

Traceback (most recent call last):
  File "Classification.py", line 13, in <module>
    SearchImage().plot_similar_images(image_path = image_list[0])
  File "/home/mike/.local/lib/python3.8/site-packages/DeepImageSearch/DeepImageSearch.py", line 132, in plot_similar_images
    plt.show(fig)
  File "/home/mike/.local/lib/python3.8/site-packages/matplotlib/pyplot.py", line 378, in show
    return _backend_mod.show(*args, **kwargs)
TypeError: show() takes 1 positional argument but 2 were given

**Comment by mikedorin** [comment]
I misread something! My apologies!

**Comment by ImASadBoy** [comment]
Hello, sorry for necroposting, but how did you fix this? I'm getting the same error.

**Comment by student0176** [comment]
Hello, sorry for necroposting, but how did you fix this? I'm getting the same error.

**Comment by student0176** [comment]
> Hello, sorry for necroposting, but how did you fix this? I'm getting the same error.
just modify the `plt.show(figure)` to `plt.show()`

**Comment by student0176** [comment]
> just modify the `plt.show(figure)` to `plt.show()`


just modify the `plt.show(figure)` to `plt.show()`
