### ISSUE TITLE
Problems with TensorFlow 

### ISSUE THREAD

**Issue by Creat1veM1nd** [TechyNilesh/DeepImageSearch#9]
Hello, 

when trying to install DeepImageSearch on a Windows machine I got this: 

```
ERROR: Cannot install deepimagesearch==1.0, deepimagesearch==1.1, deepimagesearch==1.2, deepimagesearch==1.3 and deepimagesearch==1.4 because these package versions have conflicting dependencies.

The conflict is caused by:
    deepimagesearch 1.4 depends on tensorflow
    deepimagesearch 1.3 depends on tensorflow
    deepimagesearch 1.2 depends on tensorflow
    deepimagesearch 1.1 depends on tensorflow
    deepimagesearch 1.0 depends on tensorflow`
```

I tried to install it like stated here: https://stackoverflow.com/questions/69751318/i-had-trouble-installing-python-deepimagesearch-library but also same error as mentioned there by using this. 

```
ERROR: Could not find a version that satisfies the requirement tensorflow==2.3.2 (from versions: none)
ERROR: No matching distribution found for tensorflow==2.3.
```

Digging into TensorFlow itself, it seems that it is not running on windows properly anymore beginning from version 2.11 - that would not matter, if the version required by your library would still be available

Using Windows 10 with Python 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)] on win32

Installing https://pypi.org/project/tensorflow-intel/ and changing requirements in your library did not help either.

So, what else I can do ?

Thanks in advance for any help !

**Comment by shumiyao** [comment]
same here on MacOS

**Comment by TechyNilesh** [comment]
Have you tried to install the VC code??

**Comment by Creat1veM1nd** [comment]
@TechyNilesh no error message about VS C++ 14, it's also installed on my machine. 
I did not have any TensorFlow installed before trying to install it. Beside that the error message tells me that the version is not found for installing at all.

As said: I tried to install it via the command you mentioned but I do get the error message about the version that is not found.

**Comment by TechyNilesh** [comment]
Have you tried mentioning versions like : pip install DeepImageSearch==1.4

On my windows PC, it's working fine.

**Comment by Creat1veM1nd** [comment]
> Have you tried mentioning versions like : pip install DeepImageSearch==1.4

Yes, I have. And also ==1.3 and ==1.2

This is what I got: 

```
ERROR: Could not find a version that satisfies the requirement tensorflow (from deepimagesearch) (from versions: none)
ERROR: No matching distribution found for tensorflow
```

**Comment by Creat1veM1nd** [comment]
After some research, I managed to install it. As stated on the TensorFlow Website, it only works with Python not greater than 3.10. So I installed python 3.10 next to 3.11 and with a call from the 3.10 I was able to install without errors. 

Would be nice if that would be mentioned here on your repo since your lib is depend from python version with that, in my view.

**Comment by qaixerabbas** [comment]
`ERROR: Could not find a version that satisfies the requirement tensorflow==2.3.2 (from versions: none)` 

This error refers to incompatible python version. Before installing python packages make sure you check the requirements. Best solution to this problem is to downgrade your python version.

**Comment by Creat1veM1nd** [comment]
Well, that is what I did and what I wrote in my post.
